service: pethost
frameworkVersion: '2'

plugins:
  - serverless-appsync-plugin
  - serverless-iam-roles-per-function
  - serverless-export-env
  - serverless-layers

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  environment:
    STAGE: ${self:custom.stage}
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1'

package:
  exclude:
    - package-lock.json
    - package.json

custom:
  region: ${opt:region, self:provider.region}
  stage: ${opt:stage, self:provider.stage}
  appSync:
    - ${file(serverless.appsync-api.yml)}
  serverless-layers:
    layersDeploymentBucket: ${ssm:/${self:service}/${self:custom.stage}/layer-deployment-bucket}

functions:
  confirmUserSignup: ${file(src/resources/lambda/ConfirmUserSignupLambda.yml):ConfirmUserSignup}
  createPet: ${file(src/resources/lambda/CreatePetLambda.yml):CreatePet}
  syncUsersToAlgolia: ${file(src/resources/lambda/SyncUsersToAlgoliaLambda.yml):SyncUsersToAlgolia}
  search: ${file(src/resources/lambda/SearchLambda.yml):Search}
  createBookingRequest: ${file(src/resources/lambda/CreateBookingRequestLambda.yml):CreateBookingRequest}
  acceptBookingRequest: ${file(src/resources/lambda/AcceptBookingRequestLambda.yml):AcceptBookingRequest}
  rejectBookingRequest: ${file(src/resources/lambda/RejectBookingRequestLambda.yml):RejectBookingRequest}

resources:
  Resources:
    CognitoUserPool: ${file(src/resources/cognito/CognitoUserPool.yml):CognitoUserPool}
    UserPoolInvokeConfirmUserSignupLambdaPermission: ${file(src/resources/cognito/UserPoolInvokeConfirmUserSignupLambdaPermission.yml):UserPoolInvokeConfirmUserSignupLambdaPermission}
    WebUserPoolClient: ${file(src/resources/cognito/WebUserPoolClient.yml):WebUserPoolClient}
    CognitoUserPoolOwnerGroup: ${file(src/resources/cognito/CognitoUserPoolOwnerGroup.yml):UserPoolOwnerGroup}
    CognitoUserPoolHostGroup: ${file(src/resources/cognito/CognitoUserPoolHostGroup.yml):UserPoolHostGroup}

    UsersTable: ${file(src/resources/dynamodb/UsersTable.yml):UsersTable}
    PetsTable: ${file(src/resources/dynamodb/PetsTable.yml):PetsTable}
    BookingsTable: ${file(src/resources/dynamodb/BookingsTable.yml):BookingsTable}

  Outputs:
    AwsRegion:
      Value: ${self:custom.region}

    CognitoUserPoolId:
      Value: !Ref CognitoUserPool

    WebCognitoUserPoolClientId:
      Value: !Ref WebUserPoolClient
