name: pethost
schema: schema.graphql
authenticationType: AMAZON_COGNITO_USER_POOLS
userPoolConfig:
  awsRegion: eu-west-1
  defaultAction: ALLOW
  userPoolId: !Ref CognitoUserPool
additionalAuthenticationProviders:
  - authenticationType: AWS_IAM
mappingTemplatesLocation: src/mapping-templates
mappingTemplates:
  - type: Mutation
    field: createPet
    dataSource: createPetFunction
    request: false
    response: false

  # NESTED FIELDS
  - type: Pet
    field: owner
    dataSource: usersTable

dataSources:
  - type: AMAZON_DYNAMODB
    name: petsTable
    config:
      tableName: !Ref PetsTable
  - type: AMAZON_DYNAMODB
    name: usersTable
    config:
      tableName: !Ref UsersTable
  - type: AWS_LAMBDA
    name: createPetFunction
    config:
      functionName: createPet
substitutions:
  PetsTable: !Ref PetsTable
