name: pethost
schema: schema.graphql
authenticationType: AMAZON_COGNITO_USER_POOLS
userPoolConfig:
  awsRegion: eu-west-1
  defaultAction: ALLOW
  userPoolId: !Ref CognitoUserPool
additionalAuthenticationProviders:
  - authenticationType: AWS_IAM
mappingTemplatesLocation: src/mapping-templates
mappingTemplates:
  - type: Query
    field: getMyPets
    dataSource: petsTable
  - type: Query
    field: search
    dataSource: searchFunction
    request: false
    response: false
  - type: Query
    field: listHosts
    dataSource: usersTable
  - type: Query
    field: listMyBookings
    dataSource: bookingsTable
  - type: Query
    field: listBookingsFromHost
    dataSource: bookingsTable
  - type: Query
    field: getMyProfile
    dataSource: usersTable
  - type: Query
    field: getImageUploadUrl
    dataSource: getImageUploadUrlFunction
    request: false
    response: false
  - type: Query
    field: listMyFavoriteHosts
    dataSource: favoritesTable
  - type: Mutation
    field: createPet
    dataSource: createPetFunction
    request: false
    response: false
  - type: Mutation
    field: editPet
    dataSource: petsTable
  - type: Mutation
    field: createBookingRequest
    dataSource: createBookingRequestFunction
    request: false
    response: false
  - type: Mutation
    field: acceptBookingRequest
    dataSource: acceptBookingRequestFunction
    request: false
    response: false
  - type: Mutation
    field: rejectBookingRequest
    dataSource: rejectBookingRequestFunction
    request: false
    response: false
  - type: Mutation
    field: editMyProfile
    dataSource: editMyProfileFunction
    request: false
    response: false
  - type: Mutation
    field: addHostToFavorites
    dataSource: addHostToFavoritesFunction
    request: false
    response: false

  # NESTED FIELDS
  - type: Pet
    field: owner
    dataSource: usersTable
  - type: Booking
    field: owner
    dataSource: usersTable
  - type: Booking
    field: host
    dataSource: usersTable
  - type: Booking
    field: pet
    dataSource: petsTable
  - type: PetOwnerProfile
    field: pets
    dataSource: petsTable
  - type: UnhydratedFavoriteHostsPage
    field: hosts
    dataSource: usersTable
  - type: PetHostProfile
    field: isFavorite
    dataSource: favoritesTable

dataSources:
  - type: AMAZON_DYNAMODB
    name: petsTable
    config:
      tableName: !Ref PetsTable
  - type: AMAZON_DYNAMODB
    name: usersTable
    config:
      tableName: !Ref UsersTable
  - type: AMAZON_DYNAMODB
    name: bookingsTable
    config:
      tableName: !Ref BookingsTable
  - type: AMAZON_DYNAMODB
    name: favoritesTable
    config:
      tableName: !Ref FavoritesTable
  - type: AWS_LAMBDA
    name: createPetFunction
    config:
      functionName: createPet
  - type: AWS_LAMBDA
    name: searchFunction
    config:
      functionName: search
  - type: AWS_LAMBDA
    name: createBookingRequestFunction
    config:
      functionName: createBookingRequest
  - type: AWS_LAMBDA
    name: acceptBookingRequestFunction
    config:
      functionName: acceptBookingRequest
  - type: AWS_LAMBDA
    name: rejectBookingRequestFunction
    config:
      functionName: rejectBookingRequest
  - type: AWS_LAMBDA
    name: getImageUploadUrlFunction
    config:
      functionName: getImageUploadUrl
  - type: AWS_LAMBDA
    name: editMyProfileFunction
    config:
      functionName: editMyProfile
  - type: AWS_LAMBDA
    name: addHostToFavoritesFunction
    config:
      functionName: addHostToFavorites

substitutions:
  PetsTable: !Ref PetsTable
  UsersTable: !Ref UsersTable
