UsersTable:
  Type: AWS::DynamoDB::Table
  Properties:
    BillingMode: PAY_PER_REQUEST
    KeySchema:
      - AttributeName: id
        KeyType: HASH
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
    StreamSpecification:
      StreamViewType: NEW_AND_OLD_IMAGES
    Tags:
      - Key: Environment
        Value: ${self:custom.stage}
      - Key: Name
        Value: users-table
