UsersTable:
  Type: AWS::DynamoDB::Table
  Properties:
    BillingMode: PAY_PER_REQUEST
    KeySchema:
      - AttributeName: id
        KeyType: HASH
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      - AttributeName: role
        AttributeType: S
    GlobalSecondaryIndexes:
      - IndexName: byUserType
        KeySchema:
          - AttributeName: role
            KeyType: HASH
          - AttributeName: id
            KeyType: RANGE
        Projection:
          ProjectionType: ALL
    StreamSpecification:
      StreamViewType: NEW_AND_OLD_IMAGES
    Tags:
      - Key: Environment
        Value: ${self:custom.stage}
      - Key: Name
        Value: users-table
