CognitoUserPool:
  Type: AWS::Cognito::UserPool
  Properties:
    UserPoolName: ${self:custom.stage}-pethost-user-pool
    AutoVerifiedAttributes:
      - email
    Policies:
      PasswordPolicy:
        MinimumLength: 8
        RequireLowercase: false
        RequireNumbers: false
        RequireUppercase: false
        RequireSymbols: false
    UsernameAttributes:
      - email
    Schema:
      - AttributeDataType: String
        Name: name
        Required: false
        Mutable: true
      - AttributeDataType: String
        Name: address
        Required: false
        Mutable: true
      - AttributeDataType: String
        Name: lat
        Required: false
        Mutable: true
      - AttributeDataType: String
        Name: lon
        Required: false
        Mutable: true
      - AttributeDataType: String
        Name: birthdate
        Required: false
        Mutable: true
      - AttributeDataType: String
        Name: phone_number
        Required: false
        Mutable: true
      - AttributeDataType: String
        Name: role
        Required: false
        Mutable: true
    LambdaConfig:
      PostConfirmation: !GetAtt ConfirmUserSignupLambdaFunction.Arn
